-- Product Builder Directory — February 2026 expansion
-- Verified against official product/course/community pages on 2026-03-13.
-- Safe to run multiple times.

INSERT INTO resources (
  slug,
  name,
  url,
  description,
  type,
  pillar,
  tags,
  level,
  author,
  expert_take,
  language,
  is_free,
  is_featured
) VALUES

('codex-openai', 'Codex', 'https://openai.com/codex/',
 'AI coding partner di OpenAI per task asincroni, worktree isolate, review e automazioni di team.',
 'tool', 'delivery', ARRAY['ai', 'coding', 'agents', 'openai', 'worktrees', 'automation'],
 'intermediate', 'OpenAI',
 'Nel 2026 è uno dei riferimenti per il coding agentico serio: parallelismo, contesto persistente e qualità abbastanza alta da usarlo su vero lavoro di prodotto, non solo su demo.',
 'en', true, true),

('windsurf', 'Windsurf', 'https://windsurf.com/',
 'Editor AI-first con agent, memoria del codebase, regole e workflow integrati dentro l''IDE.',
 'tool', 'delivery', ARRAY['ai', 'ide', 'coding', 'agent', 'editor'],
 'beginner', 'Windsurf',
 'Per chi vuole un editor pensato nativamente per gli agenti e non un plugin appeso sopra VS Code. Ottimo per iterazione veloce e contesto locale continuo.',
 'en', false, true),

('bolt-new', 'Bolt.new', 'https://bolt.new',
 'Builder full-stack nel browser: prompt, codice, preview e deploy in un unico loop velocissimo.',
 'tool', 'delivery', ARRAY['ai', 'fullstack', 'prototyping', 'browser', 'stackblitz'],
 'beginner', 'StackBlitz',
 'Se devi passare da idea a MVP testabile in ore, Bolt resta uno dei modi più rapidi per arrivare a qualcosa di condivisibile con utenti o stakeholder.',
 'en', true, true),

('replit-agent', 'Replit Agent', 'https://replit.com/ai',
 'Agent di Replit che genera, corregge, testa e deploya app direttamente in un ambiente cloud condivisibile.',
 'tool', 'delivery', ARRAY['ai', 'agent', 'fullstack', 'hosting', 'prototype'],
 'beginner', 'Replit',
 'Molto forte per builder non necessariamente ingegneri puri: prompti, vedi il prodotto girare, iteri e condividi senza setup locale.',
 'en', true, false),

('figma-make', 'Figma Make', 'https://www.figma.com/make/',
 'Strumento AI di Figma per trasformare idee e design in prototipi o app funzionanti con editing diretto del risultato.',
 'tool', 'design', ARRAY['ai', 'design', 'prototyping', 'ui', 'figma'],
 'beginner', 'Figma',
 'Interessante perché chiude il gap tra idea, design e prototipo interattivo dentro il posto dove i team di prodotto lavorano già.',
 'en', false, true),

('linear', 'Linear', 'https://linear.app',
 'Sistema di project execution per team di prodotto con issue tracking, roadmap, docs e sempre più AI nel workflow.',
 'tool', 'strategy', ARRAY['roadmap', 'issues', 'project-management', 'ai', 'product-development'],
 'beginner', 'Linear',
 'È il posto dove strategia e delivery si incontrano. Nel 2026 conta anche perché sta diventando il layer operativo dove coordinare umani e agenti.',
 'en', true, true),

('maze', 'Maze', 'https://maze.co/',
 'Piattaforma end-to-end per user research, test moderati e non, survey, recruit e analisi assistita da AI.',
 'tool', 'discovery', ARRAY['user-research', 'testing', 'surveys', 'ai', 'prototype-testing'],
 'beginner', 'Maze',
 'Molto utile per builder che vogliono comprimere discovery e validazione in giorni, non settimane. Ottimo ponte tra design, PM e decisioni.',
 'en', true, true),

('dovetail', 'Dovetail', 'https://dovetail.com/',
 'Customer intelligence platform che centralizza feedback, interviste, ticket e insight per guidare roadmap e priorità.',
 'tool', 'discovery', ARRAY['customer-feedback', 'research-repository', 'ai', 'insights', 'voice-of-customer'],
 'intermediate', 'Dovetail',
 'Quando il problema non è raccogliere feedback ma renderlo usabile in modo sistematico, Dovetail diventa una vera memoria di prodotto.',
 'en', true, false),

('clerk', 'Clerk', 'https://clerk.com/',
 'Authentication e user management full-stack con componenti pronti, orgs, billing hooks e sicurezza enterprise-friendly.',
 'tool', 'stack', ARRAY['auth', 'user-management', 'b2b-saas', 'security', 'components'],
 'beginner', 'Clerk',
 'Taglia via una delle parti più noiose e sensibili del build stack. Se stai costruendo un SaaS, ti fa guadagnare settimane reali.',
 'en', true, false),

('resend', 'Resend', 'https://resend.com/',
 'Email API developer-first per messaggi transazionali, marketing, inbound e template React.',
 'tool', 'stack', ARRAY['email', 'api', 'transactional', 'react-email', 'deliverability'],
 'beginner', 'Resend',
 'Email è ancora infrastruttura critica per qualsiasi prodotto. Resend è una delle scelte più pulite del momento per spedire velocemente senza impazzire.',
 'en', false, false),

('trigger-dev', 'Trigger.dev', 'https://trigger.dev/',
 'Framework TypeScript per background jobs, workflow lunghi, retries, queue e agenti AI con osservabilità inclusa.',
 'framework', 'stack', ARRAY['background-jobs', 'workflows', 'typescript', 'ai-agents', 'queues'],
 'intermediate', 'Trigger.dev',
 'Se il tuo prodotto usa agenti, scraping, generation o processi lunghi, avere un runtime serio per i job è il confine tra demo e prodotto affidabile.',
 'en', true, false),

('railway', 'Railway', 'https://railway.com/',
 'Platform per deploy di app, database e servizi con provisioning semplice e DX molto veloce.',
 'tool', 'stack', ARRAY['deploy', 'infrastructure', 'postgres', 'containers', 'hosting'],
 'beginner', 'Railway',
 'Per molti builder è l''alternativa più pragmatica quando vuoi più flessibilità di Vercel senza entrare davvero nel DevOps pesante.',
 'en', false, false),

('codex-for-builders', 'Codex for Builders', 'https://academy.openai.com/public/clubs/builders-etkn1/resources/codex-for-builders',
 'Risorsa pubblica di OpenAI Academy su workflow, setup e casi d''uso di Codex per builder. Aggiornata il 26 febbraio 2026.',
 'course', 'delivery', ARRAY['codex', 'openai', 'agents', 'workflow', 'academy'],
 'intermediate', 'OpenAI Academy',
 'Vale perché non parla di AI in astratto: mostra come inserire davvero Codex nel flusso di costruzione prodotto. Buon punto di ingresso per team e founder.',
 'en', true, true),

('builders-camp-membership', 'Builders Camp Membership', 'https://www.builderscamp.com/membership',
 'Membership formativa per diventare product builder con bootcamp, track, quest guidate, masterclass e community.',
 'course', 'meta_skill', ARRAY['product-builder', 'bootcamp', 'community', 'ai', 'shipping'],
 'beginner', 'Builders Camp',
 'Uno dei pochi programmi esplicitamente orientati a trasformare PM e product people in builder che spediscono davvero, con percorsi molto pratici.',
 'en', false, true),

('product-builder-community', 'Product Builder Community', 'https://productbuilder.community/',
 'Manifesto e community per chi lavora all''incrocio tra prodotto, design, codice e AI.',
 'community', 'meta_skill', ARRAY['product-builder', 'community', 'ai', 'career', 'manifesto'],
 'beginner', 'Product Builder Community',
 'Più che una community generica, è un posto dove il ruolo emergente del product builder viene nominato e discusso con una cornice chiara.',
 'en', true, true),

('product-growth', 'Product Growth', 'https://www.news.aakashg.com/',
 'Newsletter di Aakash Gupta con deep dive su product growth, leadership, trend tech e casi studio.',
 'newsletter', 'strategy', ARRAY['growth', 'product', 'case-studies', 'newsletter', 'career'],
 'beginner', 'Aakash Gupta',
 'Per capire come crescono davvero i prodotti moderni, è una delle newsletter più dense e utili da tenere nel loop settimanale.',
 'en', true, false),

('prodity-product-thinking', 'Prodity: Product Thinking', 'https://www.productthinking.cc/about',
 'Newsletter settimanale su AI, product management, UX design e filosofia del creare.',
 'newsletter', 'strategy', ARRAY['product', 'design', 'ai', 'ux', 'newsletter'],
 'intermediate', 'Kyle Evans',
 'Meno tattica da growth-hack, più profondità su come pensare bene mentre costruisci. Utile se vuoi alzare gusto e judgement, non solo velocità.',
 'en', true, false),

('how-i-ai', 'How I AI', 'https://www.lennysnewsletter.com/p/introducing-how-i-ai',
 'Podcast di Claire Vo con demo pratiche di come team e operatori usano AI nel lavoro quotidiano.',
 'podcast', 'meta_skill', ARRAY['ai', 'workflows', 'podcast', 'productivity', 'builder'],
 'beginner', 'Claire Vo',
 'Molto meno filosofia, molto più “fammi vedere il workflow”. Per un builder questo taglio pratico vale oro.',
 'en', true, false),

('shape-up', 'Shape Up', 'https://basecamp.com/shapeup',
 'Metodo di 37signals per shaping, betting e shipping del lavoro di prodotto con cicli da sei settimane.',
 'framework', 'delivery', ARRAY['planning', 'delivery', 'scope', 'strategy', '37signals'],
 'intermediate', 'Ryan Singer',
 'Non è nuovo, ma continua a essere uno dei framework migliori per non affogare in backlog, task factory e roadmap finte.',
 'en', true, true),

('the-mom-test', 'The Mom Test', 'https://www.momtestbook.com/',
 'Libro pratico su come fare customer conversations senza raccogliere complimenti inutili o falsi positivi.',
 'book', 'discovery', ARRAY['customer-development', 'interviews', 'discovery', 'validation', 'startup'],
 'beginner', 'Rob Fitzpatrick',
 'Se fai discovery e non vuoi mentirti, questo resta una lettura obbligatoria. Breve, concreto e ancora spietatamente utile.',
 'en', false, true),

('inspired-v2', 'INSPIRED', 'https://www.svpg.com/books/inspired-how-to-create-tech-products-customers-love-2nd-edition/',
 'Classico di Marty Cagan su come organizzare team prodotto forti e costruire prodotti tech che i clienti amano.',
 'book', 'strategy', ARRAY['product-management', 'discovery', 'delivery', 'teams', 'svpg'],
 'intermediate', 'Marty Cagan',
 'Anche nell''era AI resta fondamentale perché chiarisce cosa non cambia: judgement, product discovery, team design e responsabilità reali.',
 'en', false, true),

('harness-engineering', 'Harness engineering: leveraging Codex in an agent-first world', 'https://openai.com/index/harness-engineering/',
 'Articolo OpenAI dell''11 febbraio 2026 su come cambiano engineering workflow e strumenti quando gli agenti diventano il layer operativo principale.',
 'article', 'delivery', ARRAY['codex', 'agents', 'engineering', 'workflow', 'openai'],
 'advanced', 'OpenAI',
 'È una delle letture più utili del momento se vuoi capire come progettare un processo di build dove gli agenti non sono assistenti, ma veri operatori.',
 'en', true, true)

ON CONFLICT (slug) DO NOTHING;
